
foreground #bbbab9
background #121110

active_border_color #ffb900
inactive_border_color #322d2c
bell_border_color #9380ff

active_tab_foreground   #2a2625
active_tab_background   #bbbab9
inactive_tab_foreground #3a3433
inactive_tab_background #322d2c

tab_title_template "{fmt.fg._409cff}{bell_symbol}{activity_symbol} {fmt.fg._bbbab9}{index} {title}{fmt.fg.tab}"
active_tab_title_template "{fmt.fg._409cff}{bell_symbol}{activity_symbol} {fmt.fg._2a2625}{fmt.bold}{index}{fmt.nobold}{fmt.fg._322d2c} 󱂬 {layout_name[:2].upper()}/{num_windows}/{num_window_groups} {fmt.fg._2a2625}{fmt.bold}{title}{fmt.nobold} {fmt.fg._322d2c} {tab.active_exe}{fmt.fg.tab}"

# black
color0   #2a2625
color8   #3a3433

# red
color1   #f25022
color9   #f25022

# green
color2   #ffb900
color10  #ffb900

# yellow
color3   #7fdbca
color11  #7fdbca

# blue
color4   #9380ff
color12  #9380ff

# magenta
color5   #ee7762
color13  #ee7762

# cyan
color6   #409cff
color14  #409cff

# white
color7   #bbbab9
color15  #dfdedd
